version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - Vurolock
  ignore:
  - dependency-name: pg
    versions:
    - 8.5.1
